### ISSUE TITLE
Implement tracking of metrics over time

### ISSUE THREAD

**Issue by LoraLingrey-TriNetX** [TriNetX/dq-tools#34]
Our next "big goal" for this data quality tool is to be able to track our metrics over time and fire alerts if a metric being tracked goes out of pre-set bounds. How about we start with data volumes (broken up by data domains: http://172.31.6.156:3838/dq/dates/ tab "Prefixes") and build an alert if a volume changes by >10% from the previous measurement?

**Comment by LoraLingrey-TriNetX** [comment]
This may be bigger than this tool. Not ruling out any tracking of metrics overt time, but this may be better accomplished on ingestion or with project salmon.

**Comment by lauraevans** [comment]
One of the goals of project salmon is to get all these data we currently collect into a database, with timestamps of run dates.  I think it makes the most sense to build new tools off the project salmon database since that's the direction we want to move with DQ, rather than building new things outside the salmon framework
